name: running-test-in-macos
on: [push, pull_request]

jobs:
  running-test-in-macos:
    runs-on: macos-latest
    steps:
    - uses: action/checkout@v3
    - run: echo "running unittest in macos"
    - uses: action/setup-go@v5

      with:
        go-version: '1.21.6'

    - run: go mod tidy && go test ./...
