name: running-test-in-ubuntu
on: [push, pull_request]

jobs:
  running-test-in-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
    - run: echo "running unittest in ubuntu"
    - uses: action/setup-go@v5

      with:
        go-version: '1.21.6'

    - run: go mod tidy && go test ./...
