name: running-test-in-windows
on: [push, pull_request]

jobs:
  running-test-in-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "running unittest in windows"
    - uses: actions/setup-go@v5

      with:
        go-version: '1.21.6'

    - run: go mod tidy && go test ./...
